dist: trusty
sudo: required
language: cpp
compiler: clang

env:
   - CC=clang-6.0
   - CXX=clang++-6.0
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - clang-6.0
      - cmake

before_install:
  - sudo pip install conan
  - conan user

script:
  - mkdir build && cd build
  - conan install .. -pr ../profile/clang --build missing
  - cmake .. && make

  # Run the unit tests.
  # - ./bin/unit_tests
