dist: trusty
sudo: required
language: generic

matrix:
    include:
    - env: CXX=clang++-6.0 CC=clang-6.0

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - libstdc++-7-dev
      - clang-6.0
      - cmake

install:
  # Install conan
  - pip install conan --user
  # Automatic detection of your arch, compiler, etc.
  - conan user

script:
  - mkdir build && cd build
  - conan install .. -pr ../profile/clang --build missing
  - cmake .. && make

  # Run the unit tests.
  # - ./bin/unit_tests
