dist: trusty
sudo: required
language: cpp
compiler: clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - libstdc++-7-dev
      - clang-6.0
      - clang
      - cmake

before_install:
  - sudo pip install conan
  - conan user

script:
  - mkdir build && cd build
  - conan install .. -pr ../profile/clang --build missing
  - cmake .. && make

  # Run the unit tests.
  # - ./bin/unit_tests
