dist: trusty
sudo: required
language: cpp
compiler: clang

env:
  - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - clang-6.0
      - cmake

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo pip install conan
  - conan user

script:
  - mkdir build && cd build
  - conan install .. --build missing
  - cmake .. && make
  - ./bin/hdlc_test
