os: linux
dist: trusty
sudo: required
language: cpp

# cache:
#   directories:
#     - ~/.conan/data/

matrix:
  include:
# Clang Configuration
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - cmake
            - libc++-dev
            - libc++abi-dev
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0" BUILD_TYPE=Debug

    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - cmake
            - libc++-dev
            - libc++abi-dev
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0" BUILD_TYPE=Release

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo pip install conan
    - conan user

install:

script:
  - mkdir build && cd build
  - conan install .. --build all
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE && make
  - ./bin/hdlc_test
