dist: trusty
sudo: required
language: cpp
compiler: clang
cache:
  directories:
    - ~/.conan/data/


matrix:
  include:
    - env: MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0" BUILD_TYPE=Debug
    - env: MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0" BUILD_TYPE=Release

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - clang-6.0
      - cmake
      - libc++-dev
      - libc++abi-dev
      - libclang1-6.0

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo pip install conan
  - conan user

script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE && make
  - ./bin/hdlc_test
